"""
Factor 1 — does web traffic actually relate to revenue? (correlation / causation battery)

Mirrors the pre-Factor company battery (scripts/auto/s_t_revsurprise_factset.py):
verdict gate = company-clustered bootstrap (p_boot<0.05) AND shuffle-company surrogate
(p_surr<0.05). Run on the FULL panel (no cutoff — this is not an LLM).

Reports:
  LEVEL    web_yoy → rev_yoy            (sanity: does web track revenue growth at all)
  SURPRISE web_yoy → surprise_early     (THE test: info beyond consensus)  [+ surprise_print]
  within   within-company corr          (which quarter, not just which firm)
  TRANSFORM web_yoy / web_yoy_3m / web_accel → surprise_early   (robustness)
  SPLIT    strong vs moderate (web-revenue-dominance tiers)
  LEAD/LAG prior-quarter web_yoy → surprise_early (does X lead Y?)

OUT: factor1/outputs/f1_corr_causation.md  +  factor1/outputs/corr_results.csv
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from f1_config import OUT  # noqa: E402
from f1_stats import cluster_boot, corr, surrogate, within_company_corr  # noqa: E402

P = OUT / "panel_web.csv"
rows_md, rec = [], []


def log(s=""):
    print(s); rows_md.append(s)


def test(d, x, y, tag):
    r, pb, n = cluster_boot(d, x, y)
    ps = surrogate(d, x, y, r) if not np.isnan(r) else np.nan
    verdict = "✅" if (not np.isnan(ps) and ps < 0.05 and pb < 0.05) else (
        "·" if np.isnan(ps) else "❌")
    log(f"  {tag:34s} r={r:+.3f}  n={n:>3}  p_boot={pb:.3f}  p_surr={ps:.3f}  {verdict}")
    rec.append({"test": tag, "x": x, "y": y, "r": round(r, 4) if not np.isnan(r) else None,
                "n": n, "p_boot": round(pb, 4) if not np.isnan(pb) else None,
                "p_surr": round(ps, 4) if not np.isnan(ps) else None, "pass": verdict == "✅"})
    return r, pb, ps


def main():
    d = pd.read_csv(P)
    d["FE_FP_END"] = pd.to_datetime(d["FE_FP_END"])
    d = d.sort_values(["ticker", "FE_FP_END"])
    d["web_yoy_lag1"] = d.groupby("ticker")["web_yoy"].shift(1)  # prior-quarter X

    log("# Factor 1 — web traffic ↔ revenue (correlation / causation)\n")
    log(f"panel: {len(d)} events · {d.ticker.nunique()} tickers · "
        f"{d.FE_FP_END.min().date()}..{d.FE_FP_END.max().date()}")
    log(f"surprise_early: mean={d.surprise_early.mean()*100:+.2f}%  sd={d.surprise_early.std()*100:.2f}%  "
        f"pos-rate={(d.surprise_early>0).mean():.2f}\n")

    log("## LEVEL — does web track revenue growth at all? (sanity; expect strong for web-dominant)")
    test(d, "web_yoy", "rev_yoy", "web_yoy → rev_yoy")

    log("\n## SURPRISE — does web carry info BEYOND consensus? (THE test)")
    rE, pbE, psE = test(d, "web_yoy", "surprise_early", "web_yoy → surprise_early")
    test(d, "web_yoy", "surprise_print", "web_yoy → surprise_print")
    wc = within_company_corr(d, "web_yoy", "surprise_early")
    log(f"  within-company corr(web_yoy, surprise_early) = {wc:+.3f}  "
        f"(firm-mean removed → is it the right *quarter*, not just the right firm?)")

    log("\n## TRANSFORM robustness → surprise_early")
    for x in ["web_yoy", "web_yoy_3m", "web_accel"]:
        test(d, x, "surprise_early", f"{x} → surprise_early")

    log("\n## SPLIT by web-revenue-dominance tier → surprise_early")
    for s in ["strong", "moderate"]:
        sub = d[d.strength == s]
        test(sub, "web_yoy", "surprise_early", f"[{s}] web_yoy → surprise_early")

    log("\n## LEAD/LAG — does prior-quarter web lead the surprise?")
    test(d, "web_yoy_lag1", "surprise_early", "web_yoy(t-1) → surprise_early")

    log("\n## VERDICT")
    if not np.isnan(psE) and psE < 0.05 and pbE < 0.05:
        log(f"  ✅ Web traffic predicts revenue surprise vs point-in-time consensus "
            f"(r={rE:+.3f}, p_boot={pbE:.3f}, p_surr={psE:.3f}). Web carries info beyond analysts.")
    else:
        log(f"  ❌ NULL — web_yoy does NOT significantly predict the revenue surprise "
            f"(r={rE:+.3f}, p_boot={pbE:.3f}, p_surr={psE:.3f}).")
        log("     Consistent with F3's web thesis: web alone is a weak surprise signal "
            "(top-of-funnel, no price/mix/conversion) → the Factor-1 question is whether the "
            "earnings call rescues it (synergy, f1_05).")

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "f1_corr_causation.md").write_text(
        "<!-- generated by f1_02_corr_causation.py -->\n```\n" + "\n".join(rows_md) + "\n```\n")
    pd.DataFrame(rec).to_csv(OUT / "corr_results.csv", index=False)
    log(f"\n[written] {OUT/'f1_corr_causation.md'} · {OUT/'corr_results.csv'}")


if __name__ == "__main__":
    main()
