"""
Factor 1 — synergy validation (shuffle-company surrogate + interaction bootstrap).
PURE COMPUTATION on factor1/outputs/run_ablation_preds.csv — no LLM, $0.  Port of s_ak_validate.py.

#1 shuffle-company surrogate: is the corr firm-specific or a common cross-company artifact?
   pooled / between-company / within-company r + surrogate p (reassign each firm's true-block to
   another same-size firm's prediction positions; breaks firm↔outcome match, keeps structure).
#3 interaction: company-clustered bootstrap of arm corrs + synergy deltas
   text_on_web (fwt−fw), web_on_text (fwt−ft), synergy = fwt − (fw + ft − fin).
"""
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd

OUT = Path("/Users/junekwon/Desktop/Projects/carbon_arc/factor1/outputs")
CSV = OUT / "run_ablation_preds.csv"
ARMS = ["fin", "fin+web", "fin+text", "fin+web+text"]
lines = []


def log(s=""):
    print(s); lines.append(s)


def r(a, b):
    return np.corrcoef(a, b)[0, 1]


def main():
    df = pd.read_csv(CSV)
    true = df["true"].values
    tk = df["tkr"].values
    g = defaultdict(list)
    for i, t in enumerate(tk):
        g[t].append(i)
    bysize = defaultdict(list)
    for c, idx in g.items():
        bysize[len(idx)].append(c)
    log(f"# Factor 1 — synergy validation")
    log(f"n={len(df)} rows · {df.tkr.nunique()} companies · block sizes={ {s: len(cs) for s, cs in bysize.items()} }\n")

    log("## #1 shuffle-company surrogate (firm-specific vs common cross-company artifact)")
    log(f"  {'arm':16s} pooled  between  within   surr_p")
    rng = np.random.default_rng(7)
    for arm in ARMS:
        pred = df[arm].values
        r_pool = r(pred, true)
        cm = df.groupby("tkr").agg(p=(arm, "mean"), y=("true", "mean"))
        r_between = r(cm["p"].values, cm["y"].values)
        pdm = pred - df.groupby("tkr")[arm].transform("mean").values
        ydm = true - df.groupby("tkr")["true"].transform("mean").values
        keep = np.abs(pdm) + np.abs(ydm) > 0
        r_within = r(pdm[keep], ydm[keep])
        r_obs = abs(r_pool); cnt = 0; N = 5000
        for _ in range(N):
            pt = true.copy()
            for size, clist in bysize.items():
                if len(clist) < 2:
                    continue
                perm = rng.permutation(clist)
                for src, dst in zip(clist, perm):
                    pt[g[src]] = true[g[dst]]
            if abs(np.corrcoef(pred, pt)[0, 1]) >= r_obs:
                cnt += 1
        surr_p = (cnt + 1) / (N + 1)
        log(f"  {arm:16s} {r_pool:+.3f}  {r_between:+.3f}  {r_within:+.3f}  {surr_p:.3f}{' ✅' if surr_p<0.05 else ''}")

    log("\n## #3 interaction / synergy (company-clustered bootstrap, 5000)")
    comps = df.tkr.unique()
    rng2 = np.random.default_rng(11)
    keys = {"r_fwt": [], "text_on_web": [], "web_on_text": [], "synergy": []}
    for _ in range(5000):
        samp = rng2.choice(comps, len(comps), replace=True)
        d = pd.concat([df[df.tkr == c] for c in samp])
        y = d["true"].values
        rfin = r(d["fin"].values, y); rfw = r(d["fin+web"].values, y)
        rft = r(d["fin+text"].values, y); rfwt = r(d["fin+web+text"].values, y)
        keys["r_fwt"].append(rfwt)
        keys["text_on_web"].append(rfwt - rfw)
        keys["web_on_text"].append(rfwt - rft)
        keys["synergy"].append(rfwt - (rfw + rft - rfin))
    for k, v in keys.items():
        v = np.array(v)
        lo, hi = np.percentile(v, [2.5, 97.5])
        p = (v <= 0).mean()
        log(f"  {k:14s} mean={v.mean():+.3f}  95%CI=[{lo:+.3f},{hi:+.3f}]  p(<=0)={p:.3f}{' ✅' if p<0.05 else ''}")
    log("\n  (synergy = corr(fin+web+text) − [corr(fin+web)+corr(fin+text)−corr(fin)] > 0 ⇒ super-additive.)")

    (OUT / "f1_synergy_validation.md").write_text(
        "<!-- generated by f1_06_validate.py -->\n```\n" + "\n".join(lines) + "\n```\n")
    log(f"\n[written] {OUT/'f1_synergy_validation.md'}")


if __name__ == "__main__":
    main()
